name: CI/CD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: npm install

            - run: npm run build

            - run: npm run lint

    release:
        runs-on: ubuntu-latest
        needs:
            - test
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v3
              with:
                  # Pulls all commits (needed for semantic release to correctly version)
                  # See https://github.com/semantic-release/semantic-release/issues/1526
                  fetch-depth: "0"
                  persist-credentials: false

            # Pulls all tags (needed for semantic release to correctly version)
            - name: Fetch git tags
              run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: npm install

            - run: npm run build

            - name: Release 🚀
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release --dry-run
              working-directory: ./build